// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJFI3MUc0OTS1LHxdbNK1d91VXwTCzIY',
    appId: '1:34094672700:android:4b1f07c5baacac3093cc39',
    messagingSenderId: '34094672700',
    projectId: 'auxilium-dorona',
    storageBucket: 'auxilium-dorona.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCydsu1iTIGl0laThb114rjLnXUkQeQE8c',
    appId: '1:34094672700:ios:8d994035baa7cba093cc39',
    messagingSenderId: '34094672700',
    projectId: 'auxilium-dorona',
    storageBucket: 'auxilium-dorona.appspot.com',
    androidClientId: '34094672700-fkt4vijo39ggn7rvr3e7p03jin48hbln.apps.googleusercontent.com',
    iosClientId: '34094672700-kq39r4jova1f188pilvjafp006im5f71.apps.googleusercontent.com',
    iosBundleId: 'com.example.auxilium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCydsu1iTIGl0laThb114rjLnXUkQeQE8c',
    appId: '1:34094672700:ios:8d994035baa7cba093cc39',
    messagingSenderId: '34094672700',
    projectId: 'auxilium-dorona',
    storageBucket: 'auxilium-dorona.appspot.com',
    androidClientId: '34094672700-fkt4vijo39ggn7rvr3e7p03jin48hbln.apps.googleusercontent.com',
    iosClientId: '34094672700-kq39r4jova1f188pilvjafp006im5f71.apps.googleusercontent.com',
    iosBundleId: 'com.example.auxilium',
  );
}
